#!/usr/bin/env python
import sys

def cattfunc(j):
	#opening user demanded files
	ufile=open(j,'r+')  
	#reading file data 
	data=ufile.read()
	#closing the file to commit the data
	ufile.close()

	print '\n'+ data + '\n'


#taking  n inputs from user in command line
uinput=sys.argv[1:] 

#passing each individual files to cattfunc function to read recursively
for i in uinput:
	cattfunc(i)
	

